### ISSUE TITLE
请问训练所需的显存大概是多少？

### ISSUE THREAD

**Issue by doublecheng12** [zhengbw0324/LC-Rec#1]

**Comment by zhengbw0324** [comment]
@doublecheng12 您好！
目前我们参数设置是每个GPU的batch size为8，GPU显存为40G，训练的时候显存一般占满。不过您可以通过减少batch size，增大gradient_accumulation_steps来节省显存。

**Comment by doublecheng12** [comment]
感谢您的回复，所以是使用8*40G完成训练吗？

**Comment by zhengbw0324** [comment]
@doublecheng12 
是的，8卡40G，但实际上更少的卡也可以训练，只是速度可能较慢，或者可以尝试使用lora微调，我们也提供了代码。

**Comment by doublecheng12** [comment]
再次感谢您的回复，这份工作的想法十分的novel，请问80G的显存可以完成这样的工作吗？因为我的实验室并没有这么多的卡？也许最多只能申请1-2张a800

**Comment by zhengbw0324** [comment]
80G的单张A800我没有尝试过，但两张80G的是一定可以的。

**Comment by doublecheng12** [comment]
感谢您这么晚的回复，祝您科研顺利
