### ISSUE TITLE
关于amazon_text_emb.py的一些疑问

### ISSUE THREAD

**Issue by doublecheng12** [zhengbw0324/LC-Rec#2]
代码中似乎默认的使用的是单卡完成embedding，但是我在尝试过程中，A100-40G A40-48G都出现了OOM，请问作者是使用一张单卡40G完成这个任务的吗，还是说有一些细节我忽略了

**Comment by zhengbw0324** [comment]
@doublecheng12 您好！
LLaMA-7B进行embedding甚至仅需要24G，您是不是文本长度过长呢？

**Comment by zhengbw0324** [comment]
另外文本embedding不一定要用LLM，小模型也可以。

**Comment by doublecheng12** [comment]
您好，我使用的是Arts数据集，使用的是llama-7B，从https://huggingface.co/huggyllama/llama-7b下载得到
`def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset', type=str, default='Arts', help='Instruments / Arts / Games')
    parser.add_argument('--root', type=str, default="")
    parser.add_argument('--gpu_id', type=int, default=0, help='ID of running GPU')
    parser.add_argument('--plm_name', type=str, default='llama')
    parser.add_argument('--plm_checkpoint', type=str,
                        default='llama1')
    parser.add_argument('--max_sent_len', type=int, default=2048)
    parser.add_argument('--word_drop_ratio', type=float, default=-1, help='word drop ratio, do not drop by default')
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()

    args.root = os.path.join(args.root, args.dataset)

    device = set_device(args.gpu_id)
    args.device = device

    item_text_list = preprocess_text(args)

    plm_tokenizer, plm_model = load_plm(args.plm_checkpoint)
    if plm_tokenizer.pad_token_id is None:
        plm_tokenizer.pad_token_id = 0
    plm_model = plm_model.to(device)

    generate_item_embedding(args, item_text_list,plm_tokenizer,
                            plm_model, word_drop_ratio=args.word_drop_ratio)`
使用A100-40G。在对数据进行embedding之前，还需要任何其他的操作吗？或者是否有些参数我设置错误？

**Comment by zhengbw0324** [comment]
@doublecheng12 您好！
目前我也无法判断是什么原因引起OOM，不过如果是使用我们提供的Games数据集可以跳过数据处理过程，直接进行微调。

**Comment by doublecheng12** [comment]
感谢您的回复。
